---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      import/no-unresolved:
        enabled: false
      func-names:
        enabled: false
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
ratings:
  paths:
  - "lib/**/*"
exclude_paths:
- "node_modules/"
- "static/"
- "test/"
- "gulpfile.js"
- "cli.js"
