---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  eslint:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "src/lib/**/*.js"
  - "src/templates/**/*.js"
  - "bin/**/*.php"
exclude_paths:
- test/
- src/docs/
- src/test/
- tasks/
