---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "lib/**/*.js"
  - "bin/**/*.php"
exclude_paths:
- test/
languages:
  JavaScript: true
