---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/
---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "src/**/*.js"
  - "!src/reporters/**/*.js"
  - "bin/**/*.php"
exclude_paths:
- test/
